### ISSUE TITLE
Proof serialization/deserialization bug

### ISSUE THREAD

**Issue by Shalevos** [mir-protocol/plonky2#514]
When running:
```
let proof_bytes = proof.to_bytes()?;
let proof_from_bytes = ProofWithPublicInputs::from_bytes(proof_bytes, cd)?;
```
With (from what I can tell) any proof with the `CircuitConfig::standard_recursion_zk_config()`.
It fails with some "itertools: .zip_eq() reached end of one iterator before the other" and "failed to fill whole buffer" on a different proof.

To recreate, modify [here](https://github.com/mir-protocol/plonky2/blob/310493c293436e73096a75d0e5755816fbfe3d58/plonky2/src/plonk/recursive_verifier.rs#L203) to use the `CircuitConfig::standard_recursion_zk_config()` and run `cargo test --package plonky2 --lib --release -- plonk::recursive_verifier::tests::test_recursive_verifier --exact`

Without modification the test passes.

This also occurred with a custom circuit I was building, and seems to occur with the other test circuits in `recursive_verifier.rs`.

Am trying to work this out myself but would love some help from the dev team.

**Comment by wborgeaud** [comment]
Thanks for catching and reporting this bug @Shalevos ! I've fixed it in #515 .
The issue is that `add_virtual_proof` and `write_fri_initial_proof` functions do not take salting into account, which leads to bugs when using ZK. Since we don't usually use ZK in our tests, we failed to catch this before. So thanks for running this with ZK :)
