### ISSUE TITLE
Make plonky2 usable as a lib

### ISSUE THREAD

**Issue by Shalevos** [mir-protocol/plonky2#582]
Currently some key functions used when proving/verifying the proofs are `pub(crate)`, changing these to `pub` will make the code usable from an external crate.

Since I'm unable to create a PR myself with this due to lack of permissions, this is the git diff that is tested to solve this:

```
diff --git a/plonky2/src/gadgets/split_join.rs b/plonky2/src/gadgets/split_join.rs
index 9c9e8d3d..c8a8373b 100644
--- a/plonky2/src/gadgets/split_join.rs
+++ b/plonky2/src/gadgets/split_join.rs
@@ -13,7 +13,7 @@ impl<F: RichField + Extendable<D>, const D: usize> CircuitBuilder<F, D> {
     /// bit of the integer, with little-endian ordering.
     /// Verifies that the decomposition is correct by using `k` `BaseSum<2>` gates
     /// with `k` such that `k * num_routed_wires >= num_bits`.
-    pub(crate) fn split_le(&mut self, integer: Target, num_bits: usize) -> Vec<BoolTarget> {
+    pub fn split_le(&mut self, integer: Target, num_bits: usize) -> Vec<BoolTarget> {
         if num_bits == 0 {
             return Vec::new();
         }
diff --git a/plonky2/src/hash/merkle_proofs.rs b/plonky2/src/hash/merkle_proofs.rs
index c4188271..16470c7d 100644
--- a/plonky2/src/hash/merkle_proofs.rs
+++ b/plonky2/src/hash/merkle_proofs.rs
@@ -56,8 +56,7 @@ where
 impl<F: RichField + Extendable<D>, const D: usize> CircuitBuilder<F, D> {
     /// Verifies that the given leaf data is present at the given index in the Merkle tree with the
     /// given cap. The index is given by it's little-endian bits.
-    #[cfg(test)]
-    pub(crate) fn verify_merkle_proof<H: AlgebraicHasher<F>>(
+    pub fn verify_merkle_proof<H: AlgebraicHasher<F>>(
         &mut self,
         leaf_data: Vec<Target>,
         leaf_index_bits: &[BoolTarget],
@@ -85,7 +84,7 @@ impl<F: RichField + Extendable<D>, const D: usize> CircuitBuilder<F, D> {
     }
 
     /// Same as `verify_merkle_proof` but with the final "cap index" as extra parameter.
-    pub(crate) fn verify_merkle_proof_with_cap_index<H: AlgebraicHasher<F>>(
+    pub fn verify_merkle_proof_with_cap_index<H: AlgebraicHasher<F>>(
         &mut self,
         leaf_data: Vec<Target>,
         leaf_index_bits: &[BoolTarget],
diff --git a/plonky2/src/plonk/proof.rs b/plonky2/src/plonk/proof.rs
index 3f05ad0c..1494aef5 100644
--- a/plonky2/src/plonk/proof.rs
+++ b/plonky2/src/plonk/proof.rs
@@ -192,7 +192,7 @@ impl<F: RichField + Extendable<D>, C: GenericConfig<D, F = F>, const D: usize>
         })
     }
 
-    pub(crate) fn verify(
+    pub fn verify(
         self,
         verifier_data: &VerifierOnlyCircuitData<C, D>,
         common_data: &CommonCircuitData<F, C, D>,
diff --git a/plonky2/src/plonk/verifier.rs b/plonky2/src/plonk/verifier.rs
index e4dd41e6..5a1cae71 100644
--- a/plonky2/src/plonk/verifier.rs
+++ b/plonky2/src/plonk/verifier.rs
@@ -11,7 +11,7 @@ use crate::plonk::proof::{Proof, ProofChallenges, ProofWithPublicInputs};
 use crate::plonk::vanishing_poly::eval_vanishing_poly;
 use crate::plonk::vars::EvaluationVars;
 
-pub(crate) fn verify<F: RichField + Extendable<D>, C: GenericConfig<D, F = F>, const D: usize>(
+pub fn verify<F: RichField + Extendable<D>, C: GenericConfig<D, F = F>, const D: usize>(
     proof_with_pis: ProofWithPublicInputs<F, C, D>,
     verifier_data: &VerifierOnlyCircuitData<C, D>,
     common_data: &CommonCircuitData<F, C, D>,
```

**Comment by dlubarov** [comment]
Thanks for the patch. For verification, our intention was that `CircuitData::verify` or (if using `build_verifier`) `VerifierCircuitData::verify` would be used externally. Would one of those work for your use case?

I think exposing some Merkle proof logic sounds fine to me, but we might just want to think a bit more about the API, since it will be harder to change once public. I.e.
- should we have methods that deal with a simple Merkle root, rather than a "cap"?
- should we support other arities besides 2?
- should we take the leaf index as an int, or a sequence of bits?

Not that those features should block making some methods public, but we might want to tweak the names to "make room" for future features.

**Comment by Shalevos** [comment]
Regarding the verify function I guess it's not much of a difference to call verify just from CircuitData structs.

Regarding the Merkle proofs I think it's a must to make them public since these just enrich the way that the lib is used.
I don't know of many ZK circuits that don't use a Merkle proof at some point (usually you find yourself proving set membership of something).
I understand that you may want to add a bunch of different options in the future, but it seems logical to make what's available now usable (can always change names when it makes sense to do so).

**Comment by dlubarov** [comment]
I think we might as well make any breaking changes beforehand; they're easy changes that I can do now so it shouldn't delay this much.

I think the existing `verify_merkle_proof` API is mostly fine, my main hesitation is that the `merkle_cap` param might be confusing, since it's not really standard terminology. Also a tad ugly for applications that use simple Merkle roots to need to create a trivial `MerkleCap`. Perhaps we should make `verify_merkle_proof` work with a standard Merkle root, and add a `to_cap` suffix to methods that work with caps. Does that sound reasonable? cc @wborgeaud 

Do you have a use for `verify_merkle_proof_with_cap_index`? I think it was added as a small optimization in our recursive FRI code, where we check several proofs with the same cap index, and would rather not recompute `cap_index = le_sum(cap_index_bits)` for each. It seems pretty niche; I imagine most applications outside of FRI wouldn't have repeated cap indices.

**Comment by wborgeaud** [comment]
> I think the existing `verify_merkle_proof` API is mostly fine, my main hesitation is that the `merkle_cap` param might be confusing, since it's not really standard terminology. Also a tad ugly for applications that use simple Merkle roots to need to create a trivial `MerkleCap`. Perhaps we should make `verify_merkle_proof` work with a standard Merkle root, and add a `to_cap` suffix to methods that work with caps. Does that sound reasonable? cc @wborgeaud

Yeah that sounds good to me.

**Comment by Shalevos** [comment]
It all works great now, thanks so much!
