### ISSUE TITLE
Support deserializing proofs from slices

### ISSUE THREAD

**Issue by Sladuca** [mir-protocol/plonky2#585]
The proof serialization [`Buffer`](https://github.com/mir-protocol/plonky2/blob/3346d3f902b6b71eeef58e1dab17e2d5b8c956d6/plonky2/src/util/serialization.rs#L27) seems to only support deserialization from a `Vec<u8>`. In some environments (e.g. Solana BPF) copying into an owned `Vec<u8>` is too expensive.

May I add a read-only `RoBuffer` struct that uses a slice instead like I have [here](https://github.com/proxima-one/plonky2/blob/a356fffd97fad34b74a51c1dd71e189f56f24365/plonky2/src/util/serialization.rs#L618)?

**Comment by dlubarov** [comment]
I think that sounds good. But to avoid duplicating the read methods, I think we should remove the read methods from `Buffer` (and rename to something like `ProofWriter`), so that reads always deal with slices. Don't think there's any performance reason to read from a `Vec` rather than a slice.

cc @wborgeaud who wrote the code, in case you see an issue

**Comment by Nashtare** [comment]
I believe this can be closed?
