### ISSUE TITLE
How to wrap a lookup-table circuit in Plonky2?

### ISSUE THREAD

**Issue by ShikharJ** [mir-protocol/plonky2#867]
Hello,

Halo2 seems to have a ``struct Table`` structure available for implementing lookup-tables. Is there a corresponding functionality available in Plonky2 as well? Can someone point to an example use-case, please?

Thanks in advance.

**Comment by ShikharJ** [comment]
Can someone help me out here please?

**Comment by dlubarov** [comment]
Hi, are you using Plonky2 as in the Plonk library, not Starky (the STARK library in the same repo)? The Plonk library doesn't currently support lookups.

Starky has flexible support for permutation arguments and it's possible to implement lookups on top of that, however (since it's a STARK) it lacks support preprocessed polynomials. So it's only suitable for simple tables that can be provided by the prover and verified with simple constraints, such as a table containing the values `0, ..., 2^16 - 1`.

**Comment by ShikharJ** [comment]
Yes, that is correct. I wish to "ZK-SNARK" a model which makes use of LookUp tables. Do you think there's a way of using Starky's implementation for LookUp tables and inter-twining it with Plonky2 for "ZK-SNARK"ing the model? Or do you think it could be non-trivial? Please pardon me if my question seems a little amateur-ish, I'm quite new to the domain of ZKP systems, and this library.

**Comment by Nashtare** [comment]
@ShikharJ IDK if you're still interested in this, but lookup-table support has been integrated in the main branch, though not on crates.io yet. The  implementation isn't super optimized (yet) but provides functionality for basic lookup usecases.

**Comment by ShikharJ** [comment]
@Nashtare Thanks! I guess this issue can be closed now.

**Comment by Nashtare** [comment]
You may want to look at the additional improvements brought in by #1114 btw!
