### ISSUE TITLE
Missing CPU rows for global metadata writes

### ISSUE THREAD

**Issue by hratoanina** [mir-protocol/plonky2#988]
One of the reasons why the Memory CTL produces an invalid proof is because there are some memory writes added to the Memory Stark trace, but without corresponding writes in the CPU trace. These writes are about global metadata, and are done right before boostrapping the kernel in the CPU trace:
https://github.com/mir-protocol/plonky2/blob/5dfac7155f4717674a17ec00038f867d4e73bf98/evm/src/generation/mod.rs#L95-L105

The obvious solution is to add CPU rows with write operations somewhere in the CPU trace, but there are issues with this:
- In bootstrapping mode, constraints force all rows to write kernel code in the code segment of the kernel context, and nothing else.
- After bootstrapping, the CPU is forced to start by running the kernel `main` function, and afterwards PC constrains the execution flow.

We're not sure how to solve it, but here's two ideas we had:
- Adding another filter column during bootstrapping solely for these writes.
- Adding global metadata to `PROVER_INPUT` so that the writes could be added in ASM instructions right at the beginning of `main`.

Do you have any thoughts on these approaches, or maybe another one entirely?

**Comment by hratoanina** [comment]
A verifier bus sounds like a more versatile solution (though as far as I know the verifier shouldn't need to interact with the memory any more than these reads?). Using the CPU sounded like the easiest way to implement it, and since the metadata is part of the Stark public values, it feels like there should be an organic way to interact with it in ASM the same way you can interact with (private) input like the MPTs.

We're also not specifically working on this right now (there's also another issue in the Memory CTL check), but we may in the coming days. We'll let you know if we do!

**Comment by LindaGuiga** [comment]
As an update: we are currently working on this issue, and are considering two approaches:
- In the first, the verifier computes the missing values in the CTL products (since the verifier has access to the CTL challenges and the metadata). The verifier can then multiply the obtained product to the rest of the looking evaluations. I believe this resembles what you mentioned.
- In the second, we consider using `PROVER_INPUT` at the very beginning of  `main.asm` to add the metadata, instead of using `apply_metadata_memops`. We believe that in this case, it would suffice to link the prover private input values to the public inputs.

What do you think of these approaches?

**Comment by dlubarov** [comment]
I figure with both approaches, the verifier receives metadata as inputs, and needs a way to convince itself that the given inputs truly correspond to data in memory. With the first approach, that assurance just comes from the fact that the verifier "personally" writes them to memory.

With the second approach, it seems like the we'd need something extra, i.e. a mechanism where the verifier can securely observe certain writes done by the CPU. I think we could do that with some extra polynomial openings, one per row of the memory trace that contains a metadata field, but it might end up being a little harder to implement.

I suspect the first approach may be a bit easier to implement, but either one sounds fine I think.

**Comment by hratoanina** [comment]
For the second approach, do you think we could do the same as for example `GLOBAL_METADATA_STATE_TRIE_DIGEST_AFTER`? At the end of the EVM execution, we can hash the seven (contiguous) block metadata memory cells, store the result somewhere and declare it as public input. The verifier can then simply hash the metadata himself to check the validity of the written values.

The main advantage that I see is that changes in the ASM code don't require any modification in the verifier code, whereas any computation done on the verifier side (for the first approach) needs to also be added to the recursive verifier. This seems more complex and heavier than a simple hash and check in the case of the second approach.

**Comment by dlubarov** [comment]
Hm we had actually ripped out the public input code in EVM STARKs, since we planned to use public memory instead. It shouldn't be too hard to add back if we go that route though; we could add `public_inputs` back in `StarkEvaluationVars` similar to Starky.

I think hashing as you described would help, but it seems we'd need 4 columns in the CPU STARK to hold the hash of public values? Might be an argument for public memory.

With the public memory approach, I think the change could take the form of an extra param in `verify_cross_table_lookups`, containing an extra looking product to multiply in. Maybe an array with one product per CTL, to match the `verify_cross_table_lookups` structure, although in practice most would be 1 as the verifier would only look at the memory bus (for now at least).

**Comment by hratoanina** [comment]
Oh, I based the entire approach on the assumption that public inputs were implemented and readily accessible in `proof.public_values`. Now that I look at the code, there doesn't seem to be any constraints on them, so I suppose it's legacy code only useful for debugging?

The public memory approach seems like a nice way to take care of all "memory checks" without public values. I have one question about it, though: if I understand the approach correctly, when computing the extra looking product, the verifier needs the timestamps of the corresponding operations. For the metadata writes, it can be set at 0, but what about reads for, for example, the state trie hash root? Does the prover provide it, and since the kernel code guarantees that only one write is made at `@GLOBAL_METADATA_STATE_TRIE_DIGEST_AFTER` we know that any non-zero value must be the correct one?

**Comment by dlubarov** [comment]
Hm good point. Since it's the CPU that writes to `@GLOBAL_METADATA_STATE_TRIE_DIGEST_{BEFORE,AFTER}`, it seems like we'd separately need the verifier itself to read those fields. I think we could use `trace_length * NUM_CHANNELS` as the timestamp for those reads, since it's guaranteed to be after all writes, and it's easy to compute in both contexts (the prover's trace generation and the verifier's CTL check).

**Comment by Nashtare** [comment]
I guess this issue can be closed now? There remains constraining the public values / asserting their correctness on the verifier side but this issue was originally about the memoryCTL fix.

**Comment by wborgeaud** [comment]
> I guess this issue can be closed now? There remains constraining the public values / asserting their correctness on the verifier side but this issue was originally about the memoryCTL fix.

Good idea, closing this and opening #1164 for the public values check.
